# Generated by Django 4.2.9 on 2024-01-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Racsub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='user',
        ),
    ]
