# Generated by Django 4.2.9 on 2024-01-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Racsub_app', '0003_registeruser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registeruser',
            new_name='user',
        ),
    ]
