# Generated by Django 4.2.9 on 2024-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Racsub_app', '0006_userlist_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='useremail',
            field=models.CharField(max_length=50),
        ),
    ]
