# Generated by Django 4.2.9 on 2024-01-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Racsub_app', '0007_alter_userlist_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ชาย'), ('F', 'หญิง')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
