# Generated by Django 4.2.9 on 2024-01-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Racsub_app', '0009_userlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='status',
        ),
    ]
